plan:
	therion wip-plan.thconfig
	xdg-open out/wip.pdf

ee:
	therion wip-ee.thconfig
	xdg-open out/wip.pdf

print:
	therion print.thconfig
	xdg-open out/print.pdf

stage01:
	therion stage01.thconfig
	xdg-open out/new_park_stage_01_plan.pdf

stage02:
	therion stage02.thconfig
	xdg-open out/new_park_stage_02_plan.pdf

stage03:
	therion stage03.thconfig
	xdg-open out/new_park_stage_03_plan.pdf

stage04:
	therion stage04.thconfig
	xdg-open out/new_park_stage_04_plan.pdf

stage05:
	therion stage05.thconfig
	xdg-open out/new_park_stage_05_plan.pdf


all:
	therion stage01.thconfig
	therion stage02.thconfig
