wip:
	therion wip.thconfig
	xdg-open out/wip.pdf
	
stage01:
	therion stage01.thconfig
	xdg-open out/new_park_stage_01_plan.pdf

stage02:
	therion stage02.thconfig
	xdg-open out/new_park_stage_02_plan.pdf

stage03:
	therion stage03.thconfig
	xdg-open out/new_park_stage_03_plan.pdf

stage04:
	therion stage04.thconfig
	xdg-open out/new_park_stage_04_plan.pdf