stage01:
	therion stage01.thconfig
	xdg-open out/new_park_stage_01_plan.pdf

stage02:
	therion stage02.thconfig
	xdg-open out/new_park_stage_02_plan.pdf

stage03:
	therion stage03.thconfig
	xdg-open out/new_park_stage_03_plan.pdf